import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1720,height:980}});
await page.goto('http://localhost:3001',{waitUntil:'networkidle'});
await page.waitForTimeout(1500);
await page.screenshot({path:'/home/noah/.openclaw/workspace/company/ai-office/app/now-office.png', fullPage:true});
await page.locator('button', { hasText: 'Chief' }).first().click();
await page.waitForTimeout(1000);
await page.screenshot({path:'/home/noah/.openclaw/workspace/company/ai-office/app/now-chief.png', fullPage:true});
await browser.close();
